# Generated by Django 4.2.5 on 2023-11-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('freelance', 'Freelance')], max_length=20, null=True),
        ),
    ]
