# Generated by Django 4.2.5 on 2023-11-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='companyname',
        ),
    ]
