# Generated by Django 4.2.5 on 2023-11-29 16:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attached',
            field=models.FileField(blank=True, null=True, upload_to='static/attachments'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True, validators=[users.models.custom_email_validator]),
        ),
    ]
