# Generated by Django 4.2.5 on 2023-11-13 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('budget', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('click_total', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(blank=True, default=False, null=True)),
                ('is_assigned', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-created', 'title'],
            },
        ),
    ]
