# Generated by Django 4.2.5 on 2024-03-28 05:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "__first__"),
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("budget", models.CharField(blank=True, max_length=200, null=True)),
                ("duration", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, default="default.jpg", null=True, upload_to=""
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("click_total", models.IntegerField(blank=True, default=0, null=True)),
                ("assigned_date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "description",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                ("is_done", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "is_assigned",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "assigned",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned",
                        to="users.profile",
                    ),
                ),
                (
                    "clicked",
                    models.ManyToManyField(
                        blank=True, related_name="clicked", to="users.profile"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="projects.tag")),
            ],
            options={
                "ordering": ["-created", "title"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("budget", models.CharField(blank=True, max_length=200, null=True)),
                ("duration", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, default="default.jpg", null=True, upload_to=""
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "is_signed",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Client",
                        to="users.profile",
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Freelancer",
                        to="users.profile",
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "title"],
            },
        ),
    ]
