# Generated by Django 4.2.5 on 2023-11-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_companyname'),
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='clicked',
            field=models.ManyToManyField(blank=True, null=True, related_name='clicked', to='users.profile'),
        ),
    ]
