# Generated by Django 4.2.5 on 2023-11-18 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_companyname'),
        ('jobs', '0003_job_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='clicked',
            field=models.ManyToManyField(blank=True, related_name='clicked', to='users.profile'),
        ),
    ]
