# Generated by Django 4.2.5 on 2023-11-18 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_assigned_alter_job_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
